parser: babel-eslint
extends:
  - airbnb
  - prettier
plugins:
  - flowtype
rules:
  eqeqeq: ['error', 'allow-null']
  indent: off # prettier!
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-use-before-define: off
  no-multi-spaces: off
  no-nested-ternary: off
  no-cond-assign: ['error', 'except-parens']
  no-underscore-dangle: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-continue: off
  no-duplicate-imports: off
  no-mixed-operators: off
  no-await-in-loop: off
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: 'minimum'
  object-property-newline: off
  class-methods-use-this: off
  arrow-parens: off
  react/sort-comp: off
  react/jsx-first-prop-new-line: off
  react/jsx-indent: off
  react/jsx-indent-props: off
  react/jsx-closing-bracket-location: off
  react/jsx-filename-extension: off
  react/jsx-wrap-multilines: off
  react/forbid-prop-types: off
  react/prop-types: off
  react/require-extension: off
  react/require-default-props: off
  react/no-did-update-set-state: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
      optionalDependencies: false
  import/prefer-default-export: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/href-no-hash: off
globals:
  # Flow
  SyntheticEvent: false
  SyntheticKeyboardEvent: false
  HTMLElement: false
  HTMLInputElement: false
  $Shape: false
